@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
REM Generated by Vivado on Sun May 04 23:35:46 +0530 2025
=======
REM Generated by Vivado on Mon May 05 23:07:49 +0530 2025
>>>>>>> origin/lahiru
=======
REM Generated by Vivado on Wed May 14 17:52:03 +0530 2025
>>>>>>> lahiru
=======
REM Generated by Vivado on Wed May 14 18:13:01 +0530 2025
>>>>>>> lahiru
REM SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
<<<<<<< HEAD
echo "xvhdl --incr --relax -prj TB_Register_Bank_vhdl.prj"
call xvhdl  --incr --relax -prj TB_Register_Bank_vhdl.prj -log xvhdl.log
=======
echo "xvhdl --incr --relax -prj MUX_2_way_4_bit_tb_vhdl.prj"
call xvhdl  --incr --relax -prj MUX_2_way_4_bit_tb_vhdl.prj -log xvhdl.log
>>>>>>> origin/lahiru
=======
echo "xvhdl --incr --relax -prj adder_4_bit_Sim_vhdl.prj"
call xvhdl  --incr --relax -prj adder_4_bit_Sim_vhdl.prj -log xvhdl.log
>>>>>>> lahiru
call type xvhdl.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
