@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Sun May 04 23:35:47 +0530 2025
=======
REM Generated by Vivado on Mon May 05 23:07:50 +0530 2025
>>>>>>> origin/lahiru
REM SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
call xelab  -wto bc255be02f664c5cb5114dfa4081ffd4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TB_Register_Bank_behav xil_defaultlib.TB_Register_Bank -log elaborate.log
=======
call xelab  -wto bc255be02f664c5cb5114dfa4081ffd4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot MUX_2_way_4_bit_tb_behav xil_defaultlib.MUX_2_way_4_bit_tb -log elaborate.log
>>>>>>> origin/lahiru
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
