@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
<<<<<<< HEAD
REM Generated by Vivado on Sun May 04 23:35:48 +0530 2025
=======
REM Generated by Vivado on Mon May 05 23:07:52 +0530 2025
>>>>>>> origin/lahiru
=======
REM Generated by Vivado on Wed May 14 17:52:05 +0530 2025
>>>>>>> lahiru
REM SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
<<<<<<< HEAD
call xsim TB_Register_Bank_behav -key {Behavioral:sim_1:Functional:TB_Register_Bank} -tclbatch TB_Register_Bank.tcl -log simulate.log
=======
call xsim MUX_2_way_4_bit_tb_behav -key {Behavioral:sim_1:Functional:MUX_2_way_4_bit_tb} -tclbatch MUX_2_way_4_bit_tb.tcl -log simulate.log
>>>>>>> origin/lahiru
=======
call xsim adder_4_bit_Sim_behav -key {Behavioral:sim_1:Functional:adder_4_bit_Sim} -tclbatch adder_4_bit_Sim.tcl -log simulate.log
>>>>>>> lahiru
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
